/* =========================================================
 * 1) FACT_ORDER_ITEM (주문상품 단위)
 * ========================================================= */
CREATE TABLE FACT_ORDER_ITEM
(
    AGGREGATE_AT       DATE                                NOT NULL ,
    ORDER_ID           VARCHAR2(32)                        NOT NULL ,
    ORDER_ITEM_ID      INTEGER                             NOT NULL ,
    SELLER_ID          VARCHAR2(32)                        NOT NULL ,
    CUSTOMER_ID        VARCHAR2(32)                        NOT NULL ,
    PRODUCT_ID         VARCHAR2(32)                        NOT NULL ,
    PURCHASE_DATE_KEY  TIMESTAMP ,
    APPROVE_DATE_KEY   TIMESTAMP ,
    DELIVERED_DATE_KEY TIMESTAMP ,
    GMV                NUMBER(18 , 2) DEFAULT 0            NOT NULL ,
    FREIGHT            NUMBER(18 , 2) DEFAULT 0            NOT NULL ,
    REVENUE            NUMBER(18 , 2) DEFAULT 0            NOT NULL ,
    ORDER_STATUS       VARCHAR2(16)                        NOT NULL ,
    IS_DELIVERED_FLAG  CHAR(1)        DEFAULT 'N'          NOT NULL ,
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL ,
    UPDATED_AT         TIMESTAMP
);

COMMENT ON TABLE FACT_ORDER_ITEM IS '주문상품 단위 FACT 테이블';
COMMENT ON COLUMN FACT_ORDER_ITEM.AGGREGATE_AT IS '집계 날짜';
COMMENT ON COLUMN FACT_ORDER_ITEM.ORDER_ID IS '주문 ID';
COMMENT ON COLUMN FACT_ORDER_ITEM.ORDER_ITEM_ID IS '주문 내 상품 라인 ID(순번)';
COMMENT ON COLUMN FACT_ORDER_ITEM.SELLER_ID IS '판매자 ID';
COMMENT ON COLUMN FACT_ORDER_ITEM.CUSTOMER_ID IS '구매자(고객) ID';
COMMENT ON COLUMN FACT_ORDER_ITEM.PRODUCT_ID IS '상품 ID';
COMMENT ON COLUMN FACT_ORDER_ITEM.PURCHASE_DATE_KEY IS '구매일 키';
COMMENT ON COLUMN FACT_ORDER_ITEM.APPROVE_DATE_KEY IS '승인일 키';
COMMENT ON COLUMN FACT_ORDER_ITEM.DELIVERED_DATE_KEY IS '배송완료일 키';
COMMENT ON COLUMN FACT_ORDER_ITEM.GMV IS 'GMV(상품매출)=PRICE 합';
COMMENT ON COLUMN FACT_ORDER_ITEM.FREIGHT IS '배송비=FREIGHT_VALUE 합';
COMMENT ON COLUMN FACT_ORDER_ITEM.REVENUE IS '총매출=GMV+FREIGHT';
COMMENT ON COLUMN FACT_ORDER_ITEM.ORDER_STATUS IS '주문 상태(원천 order_status)';
COMMENT ON COLUMN FACT_ORDER_ITEM.IS_DELIVERED_FLAG IS '배송완료 여부(Y/N)';
COMMENT ON COLUMN FACT_ORDER_ITEM.CREATED_AT IS '레코드 생성 시각';
COMMENT ON COLUMN FACT_ORDER_ITEM.UPDATED_AT IS '레코드 수정 시각';
